import type { CameraBookmark, DoorConfig, SceneEnvironmentConfig, SceneFloorConfig, SceneLightConfig, TokenLightConfig, TokenVisionConfig } from "../types/sceneEnvironment";
const obj = (v: unknown): Record<string, any> => v && typeof v === "object" && !Array.isArray(v) ? v : {};
const num = (v: unknown, fallback: number, low: number, high: number) => typeof v === "number" && Number.isFinite(v) ? Math.max(low, Math.min(high, v)) : fallback;
const color = (v: unknown, fallback = "#ffffff") => typeof v === "string" && /^#[a-f0-9]{6}$/i.test(v) ? v : fallback;
const vector = (v: unknown, fallback = { x: 0, y: 0, z: 0 }) => { const o = obj(v); return { x: num(o.x, fallback.x, -500, 500), y: num(o.y, fallback.y, -100, 500), z: num(o.z, fallback.z, -500, 500) }; };
const identity = (v: unknown) => { const o = obj(v); return typeof o.id === "string" && /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}$/.test(o.id) ? { id: o.id, name: typeof o.name === "string" ? o.name.slice(0, 100) : o.id } : null; };
export function normalizeEnvironment(value?: unknown): SceneEnvironmentConfig {
  const o = obj(value); return { ambientColor: color(o.ambientColor), ambientIntensity: num(o.ambientIntensity, 1.3, 0, 5), directionalColor: color(o.directionalColor), directionalIntensity: num(o.directionalIntensity, 1.8, 0, 10), directionalPosition: vector(o.directionalPosition, { x: 10, y: 20, z: 8 }), quality: o.quality === "low" || o.quality === "high" ? o.quality : "medium", shadows: o.shadows === true, visionEnabled: o.visionEnabled === true, darkness: o.darkness === true };
}
export function normalizeDoor(value?: unknown): DoorConfig { const o = obj(value), interaction = obj(o.interaction); return { state: ["open", "locked", "destroyed", "blocked"].includes(o.state) ? o.state : "closed", hinge: o.hinge === "right" ? "right" : "left", openAngle: num(o.openAngle, 90, 15, 170), interaction: { allowPlayers: interaction.allowPlayers === true, rangeFt: num(interaction.rangeFt, 5, 1, 30) } }; }
export function normalizeLight(value: unknown): SceneLightConfig | null { const o = obj(value), id = identity(o); if (!id) return null; return { ...id, type: o.type === "spot" ? "spot" : "point", position: vector(o.position, { x: 0, y: 3, z: 0 }), target: vector(o.target), color: color(o.color), intensity: num(o.intensity, 5, 0, 100), range: num(o.range, 6, 0.1, 100), angle: num(o.angle, 60, 5, 170), shadows: o.shadows === true, floorId: identity({ id: o.floorId })?.id, visibility: o.visibility === "public" ? "public" : "gm" }; }
export function normalizeFloor(value: unknown): SceneFloorConfig | null { const o = obj(value), id = identity(o); if (!id) return null; return { ...id, elevation: num(o.elevation, 0, -100, 100), x: num(o.x, 0, 0, 500), z: num(o.z, 0, 0, 500), width: num(o.width, 8, 1, 500), depth: num(o.depth, 8, 1, 500), color: color(o.color, "#80725e"), visible: o.visible !== false }; }
export function normalizeBookmark(value: unknown): CameraBookmark | null { const o = obj(value), id = identity(o); return id ? { ...id, position: vector(o.position), target: vector(o.target), fov: num(o.fov, 45, 20, 90) } : null; }
export function normalizeVision(value?: unknown): TokenVisionConfig { const o = obj(value); return { enabled: o.enabled !== false, rangeFt: num(o.rangeFt, 60, 0, 300), angle: num(o.angle, 360, 1, 360), direction: num(o.direction, 0, -360, 360), eyeHeightFt: num(o.eyeHeightFt, 5, 0, 30), darkvisionFt: num(o.darkvisionFt, 0, 0, 300) }; }
export function normalizeTokenLight(value?: unknown): TokenLightConfig { const o = obj(value); return { enabled: o.enabled === true, type: o.type === "spot" ? "spot" : "point", color: color(o.color, "#ffce8a"), intensity: num(o.intensity, 5, 0, 100), rangeFt: num(o.rangeFt, 30, 0, 300), angle: num(o.angle, 60, 5, 170) }; }
export function tokenPerceptionFromDb(value: { visionJson?: unknown; lightJson?: unknown; visibility?: unknown; isHidden?: unknown }) { return { vision: normalizeVision(value.visionJson), light: normalizeTokenLight(value.lightJson), visibility: value.visibility === "owner_only" ? "owner_only" as const : value.visibility === undefined || value.visibility === "public" ? "public" as const : "gm_only" as const, isHidden: value.isHidden === true }; }
export function normalizeEntities<T>(value: unknown, normalize: (v: unknown) => T | null, max: number): T[] { const result: T[] = [], seen = new Set<string>(); for (const v of (Array.isArray(value) ? value.slice(0, max) : [])) { const n = normalize(v); const id = obj(n).id; if (n && !seen.has(id)) { result.push(n); seen.add(id); } } return result; }
